### ISSUE TITLE
Nested JSON

### ISSUE THREAD

**Issue by madhavajay** [eshaan7/Flask-Shell2HTTP#27]
I have an issue where the output of my cli tool is JSON but then the nested JSON inside the `report` field is all messed up and it seems I can't properly `json.loads` the main result. I wonder if there might be a way to detect json and include it properly rather than escaped inside as a substring?

**Comment by eshaan7** [comment]
It's possible to "intercept" the output providing a callback function. See [this](https://github.com/eshaan7/Flask-Shell2HTTP/blob/master/examples/custom_save_fn.py) example.

You should probably be able to write a callback function that does something like:

```python3
res: dict = future.result()  # 1. get current report
res["report"] = json.loads(res["report"]) # 2. manipulate report however u want
future._result = res # 3. set new result
```

**Comment by eshaan7** [comment]
Because of #31, I would not recommend using callback functions to modify the future's result. So you are left with 2 other options:

1. Don't change the behavior on flask-shell2http side, handle the JSON parsing on the client side. Shouldn't be too painful IMO.
1. Use a decorator to modify the JSON response and return the modified response. See below example:

```python3
from flask import make_response, jsonify
def json_parser_decorator(f):
    @functools.wraps(f)
    def decorator(*args, **kwargs):
        response = f(*args, **kwargs)
        resp_json = response.json.copy()
        resp_json["report"] = json.loads(resp_json["report"])
        return make_response(jsonify(resp_json), ret.status_code)
    return decorator

shell2http.register_command(
    endpoint="mytool", command_name="mytool", decorators=[json_parser_decorator]
)
```
