### ISSUE TITLE
use python format function

### ISSUE THREAD

**Issue by knassar702** [eshaan7/Flask-Shell2HTTP#40]
Hello @eshaan7  thanks for this project I really like it :+1: 
but I've got a simple question about the command variables, it's possible to use format string in python to select the right place of the variable?
for example 
```python
>>> command = "curl {url} --timeout {timeout}".format(url="http://google.com/",timeout=20)
"curl http://google.com/ --timeout 20"
```

**Comment by eshaan7** [comment]
Hey, this is currently not supported because it's possible to achieve this functionality in various other ways, such as:

### 1. Simply pass all args
```python3
shell2http.register_command(endpoint="curl", command_name="curl")
```
- Then in the POST request make the `args` to be `["http://google.com", "--timeout", 20]`

### 2. Using a custom bash script as an intermediary

- Create a bash script say `custom_curl.sh` with content:
```bash
curl $1 --timeout $2
```
```python3
shell2http.register_command(endpoint="curl", command_name="./custom_curl.sh")
```
- Then in the POST request make the `args` to be `["http://google.com", 20]`

**Comment by knassar702** [comment]
@eshaan7 Thanks :heart:
